export const skills = [
	"Semantic & accessible HTML",
	" Responsive Web Design",
	"Teamwork",
	"Markdown",
	"Immutability",
	"CSS BEM convention",
	"CSS Grid",
	"CSS Flexbox",
	"Styled components",
	"Database management",
	"MySQL basics",
	"React Router",
	"Redux-Saga",
	"Redux (Toolkit)",
	"React Hooks",
	"Error handling",
	"Working with API (fetch, axios)",
	"JavaScript ES6+",
	"Promises, Async/Await",
	"GitHub Pull Requests & Review",
	"Trello",
	"Scrum",
	"NPM",
	"React",
	"Git"
];
