export const skills = [
 "React.js",
 "Next.js",
 "Express.js",
 "React Hooks",
 "JavaScript ESNext",
 "TypeScript",
 "React Router",
 "Redux-Saga",
 "Redux (Toolkit)",
 "Working with API (fetch, axios)",
 "Promises, Async/Await",
 "Error handling",
 "Styled components",
 "Tailwind CSS",
 "SASS",
 "CSS BEM convention",
 "CSS Grid",
 "CSS Flexbox",
 "Semantic & accessible HTML",
 "Responsive Web Design",
 "Signal",
 "Tanstack Query",
 "Teamwork",
 "Markdown",
 "Immutability",
 "Database management",
 "MySQL basics",
 "GitHub Pull Requests & Review",
 "Trello",
 "Scrum",
 "NPM",
 "Git",
 "Debounce/Throttle"
];
